#!/bin/sh
# AxsOS açılış betiği (init tarafından shell'den önce bir kez çalıştırılır).
ip link set lo up 2>/dev/null
# Ağ kartı varsa DHCP ile adres al (QEMU user-net: 10.0.2.x)
if [ -e /sys/class/net/eth0 ]; then
    ip link set eth0 up
    udhcpc -q -t 3 -T 1 -n -i eth0 -s /etc/udhcpc.script >/dev/null 2>&1 \
        && echo "[rc] Ağ: eth0 $(ip -4 -o addr show eth0 | awk '{print $4}')"
fi
